### ISSUE TITLE
Version 1.3.0 uses newer syntax, causing compilation failure.

### ISSUE THREAD

**Issue by LMGO** [fabian-hiller/valibot#1443]
When I used Valibot in my project, version 1.1.0 worked fine, but after upgrading to 1.3.1 in the last two weeks, the build and compilation failed. The initial investigation suggests the direct cause is a change in version 1.3.0 that introduced private attributes and the "??=" syntax, causing the build to fail.

The failure message is as follows:
`
error: node_modules/valibot/dist/index.mjs: /xxx/xxxx/xxx/node_modules/valibot/dist/index.mjs: Class private methods are not enabled. Please add `@babel/plugin-transform-private-methods` to your configuration.
  3472 |        * @returns A cache key component.
  3473 |        */
> 3474 |        #stringify(input) {
       |        ^
  3475 |            const type = typeof input;
  3476 |            if (type === "string") return `"${input}"`;
  3477 |            if (type === "number" || type === "boolean") return `${input}`;
`
Thank you for looking into this issue. I've currently resolved it by locking the version. The key changes are as follows:

changes: https://github.com/open-circle/valibot/pull/1170/files#diff-1890087584a0ea664edeb245ea58ff03363d9984d637eabe820c0a8033bed1a4

<img width="1996" height="1084" alt="Image" src="https://github.com/user-attachments/assets/d5e8ec9f-cebc-4f95-8664-01977f9b58b8" />

<img width="1302" height="1298" alt="Image" src="https://github.com/user-attachments/assets/d8bb50b5-2e1e-46d9-81c8-ced2db2f18e7" />

**Comment by yslpn** [comment]
@LMGO Thanks for your feedback. 

Please tell me more about your situation? I see that [Nullish coalescing assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignment) has been available in all browsers for six years, and [private method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_elements#browser_compatibility) for five years. Do you have many users using very old browsers? Less than 4% of users worldwide use these browsers. 
<img width="305" height="87" alt="Image" src="https://github.com/user-attachments/assets/014191cb-dca8-4101-8e0c-f02767938e01" />

I'm not sure the valibot community should support such old browser versions. The most reasonable approach, in my opinion, is the one suggested by [Baseline](https://developer.mozilla.org/en-US/docs/Glossary/Baseline/Compatibility).

Use only those features that have been supported in all major browsers for at least two years.

What do you think?

**Comment by yslpn** [comment]
If we agree on which version we want to ship to users, we can discuss various tools to prevent too much new syntax from getting into the code.

Add `eslint-plugin-es-x` or `eslint-plugin-compat`, configure `target` for the `tsdown` , and add `Browserslist` to repository.

I can help with this

**Comment by LMGO** [comment]
@yslpn Thanks for your reply. In my scenario, I used React Native capabilities, and its built-in processing can be found here: https://reactnative.dev/docs/next/javascript-environment

Due to the large number of projects, it's not possible to handle all of them individually using polyfills or introducing other conversion plugins in the short term. For now, locking the version and reverting to the previous version has resolved the issue.

**Comment by fabian-hiller** [comment]
Sorry for this issue. @dosu what do you recommend to do?
